version: '3.9'

services:
  postgresql_database:
    container_name: node-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - '5432'
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: